global_parameters:
    studyfolder: /data/studies/run_recipe_1
    sessionsfolder: /data/studies/run_recipe_1/sessions
    sessions: pb12280
    batchfile: /data/studies/run_recipe_1/processing/batch.txt

recipes:
    initial_setup:
        commands:
            - create_study

    import_validate:
        commands:
            - import_dicom:
                add_image_type: 1
            - run_qc:
                modality: rawNII
                outpath: /data/studies/run_recipe_1/sessions/QC/rawNII
                customqc: no
                omitdefaults: no
                scenezip: yes
            - run_qa:
                datatype: raw_data
                configfile: /data/qunex_run_recipe/example_1/qa.yaml
                overwrite: yes

    hcp_mapping:
        commands:
            - create_session_info:
                mapping: /data/qunex_run_recipe/example_1/hcp_mapping.txt
            - create_batch:
                overwrite: append
                paramfile: /data/qunex_run_recipe/example_1/parameters.txt

    hcp_structural:
        parameters:
            customqc: no
            omitdefaults: no
            scenezip: yes
        commands:
            - setup_hcp
            - hcp_pre_freesurfer
            - hcp_freesurfer
            - hcp_post_freesurfer
            - run_qc:
                modality: T1w
                outpath: /data/studies/run_recipe_1/sessions/QC/T1w
            - run_qc:
                modality: T2w
                outpath: /data/studies/run_recipe_1/sessions/QC/T2w
            - run_qc:
                modality: myelin
                outpath: /data/studies/run_recipe_1/sessions/QC/myelin

    hcp_functional:
        parameters:
            bolds: 1
            boldsuffix: Atlas
            parelements: 1
        commands:
            - hcp_fmri_volume
            - hcp_fmri_surface
            - run_qc:
                modality: BOLD
                outpath: /data/studies/run_recipe_1/sessions/QC/BOLD
                scenetemplatefolder: /opt/qunex/qx_library/data/scenes/qc
                customqc: no
                omitdefaults: no
                scenezip: yes

    post_processing:
        parameters:
            image_target: dtseries
            bolds: 1
            boldsuffix: Atlas
            parelements: 1
        commands:
            - map_hcp_data:
                hcp_cifti_tail: _Atlas
            - create_bold_brain_masks
            - compute_bold_stats
            - create_stats_report
            - extract_nuisance_signal
            - preprocess_bold

    calculate_gbc:
        commands:
            - create_list:
                bolds: 1
                listfile: /data/studies/run_recipe_1/sessions/specs/fc_bolds.list
                bold_tail: _Atlas_s_hpss_res-mVWMWB1d_lpss.dtseries.nii
                overwrite: yes
                check: present
            - fc_compute_gbc:
                flist: /data/studies/run_recipe_1/sessions/specs/fc_bolds.list
                command: mFz:0
                targetf: /data/studies/run_recipe_1/analysis/gbc
                options: ignore=udvarsme|saveind=all|itargetf=sfolder|verbose=true
