global_parameters:
    studyfolder     : "{{$STUDY_FOLDER}}"
    sessionsfolder  : "{{$STUDY_FOLDER}}/sessions"
    overwrite       : "yes"
    sessions        : "10159"
    batchfile       : "{{$STUDY_FOLDER}}/processing/batch.txt"

recipes:
    at:
        commands:
            - create_study
            - import_bids:
                inbox   : "{{$QX_RAWDATA_FOLDER}}"
                archive : "leave"
            - create_session_info:
                mapping : "{{$QX_RECIPE_FOLDER}}/recipes/cnp/hcp_mapping.txt"
            - setup_hcp:
                sourcefolder : "{{$STUDY_FOLDER}}/sessions/10159"
            - create_batch:
                targetfile  : "{{$STUDY_FOLDER}}/processing/batch.txt"
                paramfile   : "{{$QX_RECIPE_FOLDER}}/recipes/cnp/parameters.txt"
            - hcp_pre_freesurfer
            - hcp_freesurfer
            - hcp_post_freesurfer
            - hcp_fmri_volume
            - hcp_fmri_surface
            - hcp_icafix